version: "3.8"
services:
  localstack:
    container_name: ems-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # LocalStack Gateway
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - localstack_network

networks:
  localstack_network:
    driver: bridge
